# Generated by Django 4.2.19 on 2025-02-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, max_length=10, verbose_name='класс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Учитель')], default='student', max_length=10, verbose_name='тип пользователя'),
        ),
    ]
