# Generated by Django 4.2.19 on 2025-03-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_news_options_news_author_news_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_type',
            field=models.CharField(choices=[('news', 'Новость'), ('article', 'Статья')], default='news', max_length=10, verbose_name='Тип контента'),
        ),
    ]
