# Generated by Django 4.2.19 on 2025-03-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_classinvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='author',
        ),
        migrations.RemoveField(
            model_name='material',
            name='category',
        ),
        migrations.AlterField(
            model_name='classinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20),
        ),
    ]
