# Generated by Django 4.2.19 on 2025-03-03 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_material_image_alter_material_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testquestion',
            options={'ordering': ['order', 'id'], 'verbose_name': 'вопрос теста', 'verbose_name_plural': 'вопросы теста'},
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='question',
        ),
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='test',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='points',
            field=models.PositiveIntegerField(default=1, verbose_name='Баллы'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='question_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='question_type',
            field=models.CharField(choices=[('part_a', 'Часть A (краткий ответ)'), ('part_b', 'Часть B (развернутый ответ)')], default='part_a', max_length=10, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='answer',
            field=models.TextField(blank=True, help_text='Для вопросов части A', verbose_name='Правильный ответ'),
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершен'), ('awaiting_review', 'Ожидает проверки'), ('reviewed', 'Проверен')], default='in_progress', max_length=20)),
                ('score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='app.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'test')},
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Ответ')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Правильно')),
                ('points_awarded', models.PositiveIntegerField(default=0, verbose_name='Начислено баллов')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий учителя')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.testattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.testquestion')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
