# Generated by Django 4.2.19 on 2025-03-03 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_testquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Основное изображение'),
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='question_images/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='app.testquestion')),
            ],
            options={
                'verbose_name': 'изображение вопроса',
                'verbose_name_plural': 'изображения вопросов',
                'ordering': ['order'],
            },
        ),
    ]
