# Generated by Django 4.2.19 on 2025-03-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_testquestion_image_questionimage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testattempt',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершен'), ('awaiting_review', 'Ожидает проверки'), ('reviewed', 'Проверен'), ('archived', 'В архиве')], default='in_progress', max_length=20),
        ),
    ]
