# Generated by Django 4.2.19 on 2025-03-05 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_testattempt_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='points',
            field=models.PositiveIntegerField(default=2, verbose_name='Баллы'),
        ),
    ]
