# Generated by Django 4.2.19 on 2025-03-05 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_testattempt_user_alter_testquestion_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testattempt',
            options={'ordering': ['-started_at'], 'verbose_name': 'попытка теста', 'verbose_name_plural': 'попытки тестов'},
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='завершение теста'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='max_score',
            field=models.PositiveIntegerField(default=0, verbose_name='максимальный балл'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='score',
            field=models.IntegerField(default=0, verbose_name='баллы'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='начало теста'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершен'), ('awaiting_review', 'Ожидает проверки'), ('reviewed', 'Проверен'), ('archived', 'В архиве')], default='in_progress', max_length=20, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='app.test', verbose_name='тест'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
