# Generated by Django 4.2.19 on 2025-03-07 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_testattempt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_teachers', to=settings.AUTH_USER_MODEL, verbose_name='понравилось ученикам'),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='рейтинг'),
        ),
    ]
