# Generated by Django 4.2.19 on 2025-03-07 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_user_liked_by_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disliked_by',
            field=models.ManyToManyField(blank=True, related_name='disliked_teachers', to=settings.AUTH_USER_MODEL, verbose_name='не понравилось ученикам'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_teachers', to=settings.AUTH_USER_MODEL, verbose_name='понравилось ученикам'),
        ),
    ]
