# Generated by Django 4.2.19 on 2025-03-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_user_disliked_by_alter_user_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinvitation',
            name='initiated_by',
            field=models.CharField(choices=[('teacher', 'Учитель'), ('student', 'Ученик')], default='teacher', max_length=20),
        ),
    ]
